### ISSUE TITLE
Search only in current map area

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#6] opened 2018-01-14 14:13 UTC
As it seems it always searches worldwide. It should, however, only search in the area I am currently looking at (on the map) as this is only what I am interested at.

This can dramatically increase the speed of the query (I hope).

**Comment by ENT8R** [comment] 2018-01-14 15:35
> This can dramatically increase the speed of the query (I hope).

I don't think that this will increase the speed, because this tool uses only the API of OpenStreetMap which sadly doesn't offer the possibility to search for a keyword in a specific area.
But it offers the possibility to retrieve notes by bounding box... Maybe we can make use of this and search for all notes in a specific bounding box and afterwards filter out all notes which apply to the keyword... But I don't think that this will help to increase speed...

**Comment by ENT8R** [comment] 2018-01-14 15:35
BTW: The API specification for notes can be found here:
https://wiki.openstreetmap.org/wiki/API_v0.6#Map_Notes_API

**Comment by matkoniecz** [comment] 2018-01-14 16:37
>  But I don't think that this will help to increase speed...

It would help only on extreme zoom. I am not sure is it going to help except very rare situations, probably not worth adding.

**Comment by rugk** [comment] 2018-01-14 19:32
Hu, why only with extreme zoom? Is not searching in a bounding box the same as in current map area? The bounding box must just be set to the current area.

In some way the osm website has to do this. There it is one click to find all notes in the current area.
The only difference here is yet another filter. 

Fact is it is just totally slow currently and it is totally unnecessary to find notes worldwide when I eg only want to see Germany or a big city in Germany or so.

**Comment by matkoniecz** [comment] 2018-01-14 19:37
See https://wiki.openstreetmap.org/wiki/API_v0.6#Map_Notes_API

You can either request notes containing search term, and get any notes with it - worldwide.

Or you can search for all notes within bbox.

> There it is one click to find all notes in the current area.

Is is a good idea if for given area number of notes is lower than number of notes matching search term worldwide.

**Comment by rugk** [comment] 2018-01-14 19:42
Hmm, too bad.

**Comment by ENT8R** [comment] 2018-01-14 20:21
> Fact is it is just totally slow currently

Some big overpass queries take some time too...

---
I wouldn't implement this, because the probability that there is a StreetComplete-related note at a very high zoom level is very low IMO...

So do you think that this can be closed now?

**Comment by rugk** [comment] 2018-01-14 20:25
> Some big overpass queries take some time too...

Yeah and to make them speed up, I usually just zoom in (in overpass turbo) to limit the area. 😃  Sad that this does not seem possible with notes.

**Comment by rugk** [comment] 2018-01-14 20:27
> very high zoom level

Who is talking about a very high zoom level? What is your definition of that, BTW?

We are talking about worldwide here. A lower "zoom level" is not even possible. If it would already restrict the area to one continent, it would greatly speed things up. Even more when talking about countries… And yet even more when talking about country parts… and so on, you get it. 😄  I mean usually I would first handle such notes in my local area/country.

**Comment by matkoniecz** [comment] 2018-01-14 20:29
> Who is talking about a very high zoom level? What is your definition of that, BTW?

for area visible on screen number of notes is lower than number of notes matching search term worldwide

**Comment by ENT8R** [comment] 2018-01-14 20:33
> Who is talking about a very high zoom level? What is your definition of that, BTW?

A high zoom level is for me e.g. 20. Or are we talking about something different and I completely missed it? 😄

**Comment by matkoniecz** [comment] 2018-01-14 20:38
Yeah, I should not use this term here - it was confusing.

**Comment by ENT8R** [comment] 2018-01-14 20:43
I just meant that if you would, for example, search for notes here: https://www.openstreetmap.org/#map=15/49.2212/8.7632&layers=N
the probability to find a StreetComplete related note is very low. Besides that there isn't even another non-StreetComplete-related note...

**Comment by rugk** [comment] 2018-01-15 07:59
Yeah, so as said, I consider every zoom level.

**Comment by ENT8R** [comment] 2018-01-15 13:07
> I consider every zoom level.

Mmhh... But the problem is that the API allows only a bounding box which is not larger than 25 square degrees... This doesn't sound that much to me but I have no idea what a square **degree** is... Can this be converted to square kilometers?

**Comment by rugk** [comment] 2018-01-15 23:08
Ahh, so the api can do this. So I think it may really be too small, but huh let's find out. If you can filter by city or so that would already be useful.

I also don't know what a square degree is? Can one see the current zoom level on osm or so to compare it?

**Comment by ENT8R** [comment] 2018-01-16 05:30
No. The API can't search for a keyword in a specific area... I meant the feature to search for all notes in a specific area and then filter the results afterwards...
Regarding the square degree: I think I habe to do some research...

**Comment by rugk** [comment] 2018-01-16 07:27
Ah OK, that would at least be possible.

**Comment by ENT8R** [comment] 2018-01-16 14:37
I think I figured out what a square degree is:
According to https://lists.openstreetmap.org/pipermail/talk/2007-November/020344.html it is:
> The API prevents you downloading more than
0.25 *square* degrees. That's a 0.5x0.5 degree box, or a 1x0.25
rectangle etc.

I already did some testing and Berlin has a size of about 0.23 square degrees, so it would indeed be doable! Maybe the tool can use the API to get all notes if the size is smaller than 0.25 square degrees and filter out all StreetComplete-related notes and display them to the user. But if the requested area is bigger than 0.25 square degrees, the other API will be used and notes all over the world will be retrieved...

**Comment by rugk** [comment] 2018-01-16 17:42
Yeah, maybe it would be an idea to display a "warning" to the user when the worldwide query is used?

Aka:
"Worldwide query enabled. Zoom in to get a faster query for a limited area."

So users know why things can be a but slow.

**Comment by ENT8R** [comment] 2018-01-18 18:30
This issue should be fixed now! 🎉 
@rugk could you take a look at the website and tell me if this is what you wanted?

**Comment by rugk** [comment] 2018-01-18 21:53
Wow, that looks good, …

…, but, unfortunately, behaves a bit strange. For instance with the default limit of 100 the worldwide query is faster than the local one (even if I zoom in pretty hard, so there are less than 100 notes in the area I see).

Actually, I did not see that it finished. Even in areas, where I now there are notes.

And,. it should show the warning **before** I actually click on search. (Afterwards it does not help much, as I already triggered the – potentially slow – query.) So either display it statically on the page, somewhere, or, e.g. when hovering over the button.

**Comment by rugk** [comment] 2018-01-18 21:54
As for the large zoom area: In the network tab of Firefox 57, I can actually see, that the query works and is also pretty fast. It just seems to have problems filtering the notes.

**Comment by ENT8R** [comment] 2018-01-19 05:26
Mmhh... I have to take a look at it again...

**Comment by ENT8R** [comment] 2018-01-23 17:28
> And,. it should show the warning before I actually click on search.

There is now a tooltip which opens if you hover over the search button and the bounding box is smaller than 25 square degrees

**Comment by ENT8R** [comment] 2018-01-23 17:32
Regarding the other issue:
I can't reproduce this... I searched for StreetComplete notes in Berlin and it always showed me a result...

**Comment by rugk** [comment] 2018-01-23 19:52
Here is a video:

[fetchIssue.zip](https://github.com/ENT8R/NotesReview/files/1657381/fetchIssue.zip)

**Comment by ENT8R** [comment] 2018-01-23 20:16
Ahh... I think I know what is wrong!
You searched for "streetcomplete" but in all StreetComplete-related notes, this word is never mentionned...
Instead you should search for "StreetComplete" if you don't use the worldwide query... The worldwide query can handle this (if StreetComplete is written in lowercase) but the normal Notes API searches _only_ for the **exact** value that was sent with the request (in your case "streetcomplete"). So this won't work on large zoom areas...

**Comment by rugk** [comment] 2018-01-23 22:22
Uh, you are right!

So as you may have noticed that is not a good UX when there are case differences in the search behavior for different zoom levels.
So IMHO just make it case-insensitive (probably just lower-case the input string before filtering it or so). If you really want, you could add another checkbox to toggle the state between case-sensitive and case-insensitive.

**Comment by ENT8R** [comment] 2018-01-24 13:02
> So IMHO just make it case-insensitive (probably just lower-case the input string before filtering it or so). If you really want, you could add another checkbox to toggle the state between case-sensitive and case-insensitive.

But then it would not work for the query "StreetComplete" which would be "streetcomplete" and for this query no notes are found...

**Comment by rugk** [comment] 2018-01-24 14:07
So then make all queries case-sensutuve, then. 😄 In any case inconsistent behaviour is not good.

**Comment by ENT8R** [comment] 2018-01-24 14:14
But how??? The API for large zoom areas is the problem... The tool gets all notes in the visible area and filters out all fitting notes with the specified query **afterwards**. The problem is that the Map Notes Search API can't search for a query in a specific area but only on the whole world... I have no chance to make the queries case-sensitive as this is all done on the servers of OSM...

**Comment by rugk** [comment] 2018-01-24 14:25
>The tool gets all notes in the visible area and filters out all fitting notes with the specified query afterwards. 

And this filtering is done locally, if I am correct. So you can influence that...

So if I understand it correctrly, it is like that:
Notes API for high zooms: download all quests -> case-sensitive matching on the client
Worldwide query for low zoom levels: passes query directly to API (this is case-insensitive)

So you cannot influence the worldwide query, but the lcoal filtering of the Notes API, can't you?
Don't if thatn really helps, but [here is how to do `contains` with jQuery in an case-insensitive way](https://stackoverflow.com/questions/2196641/how-do-i-make-jquery-contains-case-insensitive-including-jquery-1-8/2196683#2196683).

**Comment by ENT8R** [comment] 2018-01-24 14:40
> So you cannot influence the worldwide query, but the lcoal filtering of the Notes API, can't you?

Yes that's right... But that would result in converting "streetcomplete" to "Streetcomplete", but what we want is "StreetComplete"...

**Comment by rugk** [comment] 2018-01-24 18:17
No, no don't convert anything. Talking only about high zoom levels with Notes API here, this is the workflow:
1. Download all quests in the area.
2. Now filter it, **without caring about the case** (of course this is possible in JavaScript, see jQuery contains linked above). That means you include "streetcomplete", "StreetComplete" and "StReTCoMpLeTe" in the results. Just do it case-**in**sensitive.

I.e. that should work: https://github.com/ENT8R/NotesReview/pull/13

**Closed** 2018-01-25 12:58 UTC
