### ISSUE TITLE
Query on e.g. onosm.org doesn't work anymore

### ISSUE THREAD

**Issue by JillisE** [ENT8R/NotesReview#73] opened 2021-05-29 17:55 UTC
As in the title: when I use the string onosm.org in the query to find notes generated by that website, the results include notes with just osm.org in them, and even any other .org (and other substrings?).
It's also much slower than it used to be.

**Comment by ENT8R** [comment] 2021-05-30 13:11
The problem here seems to be that the text query tokenizes the input using whitespaces and punctuation marks as delimiters, and applies a logical OR to all tokens. As the search term "onosm.org" obviously includes a dot, the results will either include the term "onosm" OR "org".
What happens when you put quotation marks around your input? Putting quotation marks around it should usually only return exact matches without further tokenization.

**Comment by JillisE** [comment] 2021-05-30 15:18
When I put quotation marks around it, I get the results I want.
But why do I have to start doing that when I didn't need the quotation marks before?

Also, the performance is still quite worse.

**Comment by ENT8R** [comment] 2021-05-30 20:43
> But why do I have to start doing that when I didn't need the quotation marks before?

Well, the backend is completely new and the search function of the new backend is much more powerful than before and allows even more optimizations/additions in the future 😏
The quotation marks tell the backend that the search string should be handled as an exact phrase which should occur **exactly like that** in the notes being returned. I will think about what might be the best thing to do here: either assume all queries are exact queries or leave the choice to the user but show a message about the difference between exact and other queries.

I can also reproduce the performance problem and am currently investigating why this (and also other) query is so slow...

**Comment by Lee-Carre** [comment] 2022-01-16 02:07
@ENT8R

Suggestion for the long-term, given your description of the backend reimplementation; RegEx pattern-matching.

**Comment by ArcaneDots** [comment] 2022-03-12 19:20
Querying with just "onosm" (no quotes) does seem to fetch all onosm.org generated notes.

Wondering if providing a simple directions/examples would reduce confusion on how to preform searches. Could help with any further improvements/troubleshooting. Maybe using the existing tooltip.

**Comment by ENT8R** [comment] 2022-03-14 00:11
I'm currently working on some improvements regarding the search and this specific issue should be fixed, as the search now pays attention to the dot in onosm<b>.</b>org. The filtering is a little bit more strict than before in general, but this will likely reduce the amount of false-positive results.

**Closed by ENT8R** 2022-03-14 00:11 UTC
