### ISSUE TITLE
Favors recent notes?

### ISSUE THREAD

**Issue by rugk** [ENT8R/NotesReview#39] opened 2019-10-01 19:36 UTC
Can it be this has a littler bias (:wink:) and favors recently created notes? In the list view, you only rarely see some older than 1 day and only hardly > 14 days.

opened app without changing settings, used first auto-search result

**Comment by ENT8R** [comment] 2019-10-02 21:18
Yes, it's true that only more recent notes are shown. This is mainly because the OpenStreetMap API supplies the notes that way. See also https://github.com/openstreetmap/openstreetmap-website/blob/83983bfc6a31c2da0af6f18137cd31ba40519191/app/controllers/api/notes_controller.rb#L301 for the current implementation. (sorted by the value of updated_at in a descending order).
But to find older notes, you can simply change the value of the datepicker field, can't you?

**Comment by rugk** [comment] 2019-10-03 19:17
The question is what is more useful for Mappers:
* When your recent note is picked up (so) fast (that you cannot even solve it by yourself; e.g. I sometimes create notes just for myself and want to fix them in a few hours by myself, so it may be annoying/useless work to get it fixed by anyone else)
* Or when mappers fix old issues and clean up these things, (though old issues may be/tend to be more outdated or not accurate anymore or so)

:thinking:

**Comment by ENT8R** [comment] 2019-10-03 19:58
I tend to say that more recent notes are still the ones which are more easy to solve.
Very often, old notes are unresolved because of unclear or incomplete information, like you already said, and thus not easily solvable for armchair mappers who want to make a quick improvement to the map...
But once https://github.com/openstreetmap/openstreetmap-website/pull/2381 is merged, I can implement a new checkbox and then the mapper can decide on their own whether recent or rather old notes should be shown 😄

**Comment by rugk** [comment] 2019-10-03 20:06
Maybe for the defaults, we could get a good mix? Like 30% old issues, and 70% new issues??

Defaults matter, you know. I personally would never change the date range or so, unless I am looking for a specific note, if I just want to "help and solve some notes".

**Comment by ENT8R** [comment] 2019-10-03 20:11
I think that would be unexpected behaviour and maybe even considered as a bug by some users who really only want to find the newest (or oldest) notes...

**Comment by rugk** [comment] 2019-10-03 20:47
I basically want to find the notes that are most useful to solve… :thinking:

**Comment by ENT8R** [comment] 2019-10-04 12:48
But IMO it does always differ what mappers consider as useful to solve. Some mappers maybe want to solve only new notes, some others only old notes and I wouldn't really want to prescribe what kind of notes are favored by the website...

**Comment by xuiqzy** [comment] 2020-02-17 12:31
But currently new notes are favored. I know it was not your explicit decision, but nonetheless these are the notes favored by the website.
So if another ordering seems more sensible as default as the current one and is easily implementable, it is definitely worth thinking about as an improvement.

Only forcing the user to select an ordering would remove the website from the position to present a default, but I think that is a bad user experience and not helpful. Users who explicitly want a different sorting, other than trusting the default of the website, will find it, if the option is provided.

**Comment by ENT8R** [comment] 2020-02-20 15:00
With https://github.com/ENT8R/NotesReview/commit/e5404b03b949bc3430ba8084a8adfb7814a55e09 the default behavior is that the last 100 notes with the latest **creation date** are displayed. Nevertheless the user can choose between 4 sorting options: by creation date (descending), creation date (ascending), last update (descending), last update (ascending).
I think that the option to sort notes is prominent enough and easy to understand, so I would not want to implement another solution with other default values.

**Closed by ENT8R** 2020-02-20 15:00 UTC
